// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaCPzpn3zf1LPP4ZmRDgKxPOcznmtbRU8',
    appId: '1:1028097243563:web:24e202c1f39e3394fa3aee',
    messagingSenderId: '1028097243563',
    projectId: 'loungefood-eeb7e',
    authDomain: 'loungefood-eeb7e.firebaseapp.com',
    storageBucket: 'loungefood-eeb7e.appspot.com',
    measurementId: 'G-D71J8K00XW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFvvP2NOI5J3JG36RTtAjqaIP_bzJu_MQ',
    appId: '1:1028097243563:android:b015f09773cb58ddfa3aee',
    messagingSenderId: '1028097243563',
    projectId: 'loungefood-eeb7e',
    storageBucket: 'loungefood-eeb7e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9OCs4_4X3AUg4lURDDctt8zInrenASVk',
    appId: '1:1028097243563:ios:b8ef45bbe463aca3fa3aee',
    messagingSenderId: '1028097243563',
    projectId: 'loungefood-eeb7e',
    storageBucket: 'loungefood-eeb7e.appspot.com',
    iosClientId: '1028097243563-uhonsrjvd6g0icqdomlb6s2pambuhoh9.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodOrder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9OCs4_4X3AUg4lURDDctt8zInrenASVk',
    appId: '1:1028097243563:ios:b8ef45bbe463aca3fa3aee',
    messagingSenderId: '1028097243563',
    projectId: 'loungefood-eeb7e',
    storageBucket: 'loungefood-eeb7e.appspot.com',
    iosClientId: '1028097243563-uhonsrjvd6g0icqdomlb6s2pambuhoh9.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodOrder',
  );
}
